[package]
name = "apikeys"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
axum = "0.8.8"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio"] }
uuid = { version = "1.20.0", features = ["v4"] }
